### ISSUE TITLE
Installer icon is ignored when using build.json

### ISSUE THREAD

**Issue by goffioul** [apache/cordova-electron#73]
## Problem
When using a build.json file to customize the build output, the installer icon defined in config.xml is ignored.

### What is expected to happen?
The installer icon is used for the executables generated.

### What does actually happen?
Default electron icon is used for the executables generated.

## Information
Define electron platform in config,xml with an installer icon, e.g.:
```
    <platform name="electron">
        ...
        <icon src="res/electron/installer.png" target="installer" />
    </platform>
```

Build app for electron, the file `platforms/electron/build/builder-effective-config.yaml` contains the following lin (in `win` section):
```
  icon: installer.png
```

Now create a build.json file with the following content:
```
{
        "electron": {
                "windows": {
                        "package": [ "zip" ]
                }
        }
}
```

Build the app again for electron. The file `platforms/electron/build/builder-effective-config.yaml` does not have the icon defined anymore and electron-builder complains with:
```
  • default Electron icon is used reason=application icon is not set
```

### Environment, Platform, Device
Windows 10

### Version information
cordova 9.0.0
cordova-electron 1.0.2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by GedasGa** [comment]
This has been fixed in the #45 PR and will be released in the `1.1.0` version.

**Comment by Polm90** [comment]
I'm still having the issue with cordova-electron 3.1.0 and cordova 11.0.0.

How can I solve this issue?
